### ISSUE TITLE
Add ARM Arch Support

### ISSUE THREAD

**Issue by Persi** [tianon/docker-postgres-upgrade#85] opened 2023-12-19 07:15 UTC
Currently all provided images only support amd64 architecture. Would it be possible to add support for arm based architectures as well?

**Comment by tianon** [comment] 2023-12-19 07:17
Duplicate of #43, #82

**Closed by tianon** 2023-12-19 07:17 UTC

**Comment by tianon** [comment] 2025-08-29 03:53
See https://github.com/tianon/docker-postgres-upgrade/pull/116 and https://github.com/tianon/docker-postgres-upgrade/issues/99#issuecomment-3235566575:

> I've got an approach I'm happy with -- the middle ground I've chosen is that the latest _target_ version (that's currently 17) will get arm64 builds so that I'm not building the _full_ matrix for arm64, and I think that should satisfy a decent chunk of use cases while still being a reasonable added load (only four extra emulated builds instead of ten).

> Updated images are pushed now: https://oci.dag.dev/?image=tianon/postgres-upgrade:16-to-17@sha256:8a8b3f00ac46b6c749e593267c2f61df2901f3175027bc25c75ee0bbcc5748ef
